# Generated by Django 5.2.3 on 2025-06-22 06:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=100, verbose_name='Тип сотрудника')),
            ],
            options={
                'verbose_name': 'Тип сотрудника',
                'verbose_name_plural': 'Типы сотрудников',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место работы')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='Национальность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='employees/images/', verbose_name='Изображение')),
                ('birth_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место рождения')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('reception_schedule', models.CharField(blank=True, max_length=255, null=True, verbose_name='График приема')),
                ('employee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.employeetype', verbose_name='Тип сотрудника')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
