# Generated by Django 5.2.3 on 2025-06-23 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=250, verbose_name='Название сектора')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес сектора')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сектора')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sectors/images/', verbose_name='Изображение сектора')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Сектор',
                'verbose_name_plural': 'Секторы',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
